// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type CaseStudyDocumentDataSlicesSlice =
  | ContactSlice
  | CarousalSlice
  | ProjectSpec2Slice
  | AboutTimelineSlice
  | ProjectSpec1Slice
  | RichTextSlice;

/**
 * Content for Projects documents
 */
interface CaseStudyDocumentData {
  /**
   * Heading field in *Projects*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Body field in *Projects*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Image field in *Projects*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Projects*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CaseStudyDocumentDataSlicesSlice> /**
   * Meta Description field in *Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: case_study.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Projects*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: case_study.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Projects document from Prismic
 *
 * - **API ID**: `case_study`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CaseStudyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CaseStudyDocumentData>,
    "case_study",
    Lang
  >;

type OperationsDocumentDataSlicesSlice =
  | OperationsSlice
  | OperationsHeaderSlice;

/**
 * Content for Operations documents
 */
interface OperationsDocumentData {
  /**
   * Heading field in *Operations*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: operations.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Body field in *Operations*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: operations.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Image field in *Operations*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: operations.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Operations*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: operations.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<OperationsDocumentDataSlicesSlice> /**
   * Meta Description field in *Operations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: operations.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Operations*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: operations.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Operations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: operations.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Operations document from Prismic
 *
 * - **API ID**: `operations`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OperationsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OperationsDocumentData>,
    "operations",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | OperationsSlice
  | OperationsHeaderSlice
  | CaseStudySlice
  | ProjectsHeaderSlice
  | SecondaryCtaSlice
  | ContactFormSlice
  | ContactHeaderSlice
  | ServiceProcessSlice
  | ServiceBenefitsSlice
  | ServiceFeaturesSlice
  | ServiceFieldsSlice
  | ServiceHeaderSlice
  | AboutTimelineSlice
  | AboutHistorySlice
  | AboutHeaderSlice
  | ContactSlice
  | FaqSlice
  | ServicesSlice
  | CtaSlice
  | HomeTeamSlice
  | HomeAbout2Slice
  | HomeAboutSlice
  | RichTextSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * CTA Button field in *Settings → Navigation*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: settings.navigation[].cta_button
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  cta_button: prismic.BooleanField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Fallback OG image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.fallback_og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fallback_og_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | CaseStudyDocument
  | OperationsDocument
  | PageDocument
  | SettingsDocument;

/**
 * Primary content in *AboutHeader → Primary*
 */
export interface AboutHeaderSliceDefaultPrimary {
  /**
   * Title field in *AboutHeader → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: about_header.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Default variation for AboutHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutHeader*
 */
type AboutHeaderSliceVariation = AboutHeaderSliceDefault;

/**
 * AboutHeader Shared Slice
 *
 * - **API ID**: `about_header`
 * - **Description**: AboutHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutHeaderSlice = prismic.SharedSlice<
  "about_header",
  AboutHeaderSliceVariation
>;

/**
 * Primary content in *AboutHistory → Primary*
 */
export interface AboutHistorySliceDefaultPrimary {
  /**
   * Title field in *AboutHistory → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: about_history.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Body field in *AboutHistory → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_history.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *AboutHistory → Items*
 */
export interface AboutHistorySliceDefaultItem {
  /**
   * Image field in *AboutHistory → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_history.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for AboutHistory Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutHistorySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutHistorySliceDefaultPrimary>,
  Simplify<AboutHistorySliceDefaultItem>
>;

/**
 * Slice variation for *AboutHistory*
 */
type AboutHistorySliceVariation = AboutHistorySliceDefault;

/**
 * AboutHistory Shared Slice
 *
 * - **API ID**: `about_history`
 * - **Description**: AboutHistory
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutHistorySlice = prismic.SharedSlice<
  "about_history",
  AboutHistorySliceVariation
>;

/**
 * Primary content in *AboutTimeline → Primary*
 */
export interface AboutTimelineSliceDefaultPrimary {
  /**
   * Title field in *AboutTimeline → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: about_timeline.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *AboutTimeline → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_timeline.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *AboutTimeline → Items*
 */
export interface AboutTimelineSliceDefaultItem {
  /**
   * Title field in *AboutTimeline → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_timeline.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Timeline field in *AboutTimeline → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_timeline.items[].timeline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  timeline: prismic.RichTextField;

  /**
   * Date field in *AboutTimeline → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_timeline.items[].date
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  date: prismic.RichTextField;
}

/**
 * Default variation for AboutTimeline Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutTimelineSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutTimelineSliceDefaultPrimary>,
  Simplify<AboutTimelineSliceDefaultItem>
>;

/**
 * Slice variation for *AboutTimeline*
 */
type AboutTimelineSliceVariation = AboutTimelineSliceDefault;

/**
 * AboutTimeline Shared Slice
 *
 * - **API ID**: `about_timeline`
 * - **Description**: AboutTimeline
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutTimelineSlice = prismic.SharedSlice<
  "about_timeline",
  AboutTimelineSliceVariation
>;

/**
 * Primary content in *Carousal → Primary*
 */
export interface CarousalSliceDefaultPrimary {
  /**
   * Title field in *Carousal → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: carousal.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Body field in *Carousal → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousal.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *Carousal → Items*
 */
export interface CarousalSliceDefaultItem {
  /**
   * Image field in *Carousal → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carousal.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *Carousal → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: carousal.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Description field in *Carousal → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousal.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Carousal Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarousalSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarousalSliceDefaultPrimary>,
  Simplify<CarousalSliceDefaultItem>
>;

/**
 * Slice variation for *Carousal*
 */
type CarousalSliceVariation = CarousalSliceDefault;

/**
 * Carousal Shared Slice
 *
 * - **API ID**: `carousal`
 * - **Description**: Carousal
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarousalSlice = prismic.SharedSlice<
  "carousal",
  CarousalSliceVariation
>;

/**
 * Primary content in *CaseStudy → Items*
 */
export interface CaseStudySliceDefaultItem {
  /**
   * Case Study field in *CaseStudy → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.items[].case_study
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  case_study: prismic.ContentRelationshipField;
}

/**
 * Default variation for CaseStudy Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CaseStudySliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<CaseStudySliceDefaultItem>
>;

/**
 * Slice variation for *CaseStudy*
 */
type CaseStudySliceVariation = CaseStudySliceDefault;

/**
 * CaseStudy Shared Slice
 *
 * - **API ID**: `case_study`
 * - **Description**: CaseStudy
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CaseStudySlice = prismic.SharedSlice<
  "case_study",
  CaseStudySliceVariation
>;

/**
 * Primary content in *Contact → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * Title field in *Contact → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Body field in *Contact → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *Contact → Items*
 */
export interface ContactSliceDefaultItem {
  /**
   * Icon field in *Contact → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<"Email" | "Phone" | "Office">;

  /**
   * Heading field in *Contact → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Description field in *Contact → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Link field in *Contact → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.items[].link
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  link: prismic.RichTextField;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  Simplify<ContactSliceDefaultItem>
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Primary content in *ContactForm → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
  /**
   * Heading field in *ContactForm → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Image field in *ContactForm → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Primary content in *ContactHeader → Primary*
 */
export interface ContactHeaderSliceDefaultPrimary {
  /**
   * Heading field in *ContactHeader → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_header.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *ContactHeader → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_header.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for ContactHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactHeader*
 */
type ContactHeaderSliceVariation = ContactHeaderSliceDefault;

/**
 * ContactHeader Shared Slice
 *
 * - **API ID**: `contact_header`
 * - **Description**: ContactHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactHeaderSlice = prismic.SharedSlice<
  "contact_header",
  ContactHeaderSliceVariation
>;

/**
 * Primary content in *Cta → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * Title field in *Cta → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Body field in *Cta → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Image field in *Cta → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Button1 field in *Cta → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.primary.button1text
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button1text: prismic.LinkField;

  /**
   * Button1Text field in *Cta → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.primary.button1link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button1link: prismic.KeyTextField;

  /**
   * Button2 field in *Cta → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.primary.button2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button2: prismic.LinkField;

  /**
   * Button2Text field in *Cta → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.primary.button2text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button2text: prismic.KeyTextField;
}

/**
 * Default variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Primary content in *Faq → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Title field in *Faq → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Body field in *Faq → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *Faq → Items*
 */
export interface FaqSliceDefaultItem {
  /**
   * Question field in *Faq → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].question
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  question: prismic.RichTextField;

  /**
   * Answer field in *Faq → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  Simplify<FaqSliceDefaultItem>
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Body field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button Label field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *HomeAbout → Primary*
 */
export interface HomeAboutSliceDefaultPrimary {
  /**
   * Title field in *HomeAbout → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Body field in *HomeAbout → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Image field in *HomeAbout → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for HomeAbout Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeAboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeAboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeAbout*
 */
type HomeAboutSliceVariation = HomeAboutSliceDefault;

/**
 * HomeAbout Shared Slice
 *
 * - **API ID**: `home_about`
 * - **Description**: HomeAbout
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeAboutSlice = prismic.SharedSlice<
  "home_about",
  HomeAboutSliceVariation
>;

/**
 * Primary content in *HomeAbout2 → Primary*
 */
export interface HomeAbout2SliceDefaultPrimary {
  /**
   * Title field in *HomeAbout2 → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about2.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Body field in *HomeAbout2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about2.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Image field in *HomeAbout2 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about2.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Button1 field in *HomeAbout2 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about2.primary.button1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button1: prismic.LinkField;

  /**
   * Button1Text field in *HomeAbout2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about2.primary.button1text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button1text: prismic.KeyTextField;

  /**
   * Button2 field in *HomeAbout2 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about2.primary.button2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button2: prismic.LinkField;

  /**
   * Button2Text field in *HomeAbout2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about2.primary.button2text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button2text: prismic.KeyTextField;
}

/**
 * Default variation for HomeAbout2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeAbout2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeAbout2SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeAbout2*
 */
type HomeAbout2SliceVariation = HomeAbout2SliceDefault;

/**
 * HomeAbout2 Shared Slice
 *
 * - **API ID**: `home_about2`
 * - **Description**: HomeAbout2
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeAbout2Slice = prismic.SharedSlice<
  "home_about2",
  HomeAbout2SliceVariation
>;

/**
 * Primary content in *HomeTeam → Primary*
 */
export interface HomeTeamSliceDefaultPrimary {
  /**
   * Title field in *HomeTeam → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home_team.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Body field in *HomeTeam → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_team.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *HomeTeam → Items*
 */
export interface HomeTeamSliceDefaultItem {
  /**
   * Image field in *HomeTeam → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_team.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *HomeTeam → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_team.items[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Position field in *HomeTeam → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home_team.items[].position
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  position: prismic.TitleField;

  /**
   * Body field in *HomeTeam → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_team.items[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for HomeTeam Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeTeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeTeamSliceDefaultPrimary>,
  Simplify<HomeTeamSliceDefaultItem>
>;

/**
 * Slice variation for *HomeTeam*
 */
type HomeTeamSliceVariation = HomeTeamSliceDefault;

/**
 * HomeTeam Shared Slice
 *
 * - **API ID**: `home_team`
 * - **Description**: HomeTeam
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeTeamSlice = prismic.SharedSlice<
  "home_team",
  HomeTeamSliceVariation
>;

/**
 * Primary content in *Operations → Primary*
 */
export interface OperationsSliceDefaultPrimary {
  /**
   * Heading field in *Operations → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: operations.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Body field in *Operations → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: operations.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *Operations → Items*
 */
export interface OperationsSliceDefaultItem {
  /**
   * Operations field in *Operations → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: operations.items[].operations
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  operations: prismic.ContentRelationshipField;
}

/**
 * Default variation for Operations Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OperationsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OperationsSliceDefaultPrimary>,
  Simplify<OperationsSliceDefaultItem>
>;

/**
 * Slice variation for *Operations*
 */
type OperationsSliceVariation = OperationsSliceDefault;

/**
 * Operations Shared Slice
 *
 * - **API ID**: `operations`
 * - **Description**: Operations
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OperationsSlice = prismic.SharedSlice<
  "operations",
  OperationsSliceVariation
>;

/**
 * Primary content in *OperationsHeader → Primary*
 */
export interface OperationsHeaderSliceDefaultPrimary {
  /**
   * Heading field in *OperationsHeader → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: operations_header.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Body field in *OperationsHeader → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: operations_header.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * image1 field in *OperationsHeader → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: operations_header.primary.image1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image1: prismic.ImageField<never>;

  /**
   * image2 field in *OperationsHeader → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: operations_header.primary.image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;
}

/**
 * Default variation for OperationsHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OperationsHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OperationsHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OperationsHeader*
 */
type OperationsHeaderSliceVariation = OperationsHeaderSliceDefault;

/**
 * OperationsHeader Shared Slice
 *
 * - **API ID**: `operations_header`
 * - **Description**: OperationsHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OperationsHeaderSlice = prismic.SharedSlice<
  "operations_header",
  OperationsHeaderSliceVariation
>;

/**
 * Primary content in *ProjectSpec1 → Primary*
 */
export interface ProjectSpec1SliceDefaultPrimary {
  /**
   * Title field in *ProjectSpec1 → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: project_spec1.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Body field in *ProjectSpec1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_spec1.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *ProjectSpec1 → Items*
 */
export interface ProjectSpec1SliceDefaultItem {
  /**
   * Image field in *ProjectSpec1 → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_spec1.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ProjectSpec1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectSpec1SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectSpec1SliceDefaultPrimary>,
  Simplify<ProjectSpec1SliceDefaultItem>
>;

/**
 * Slice variation for *ProjectSpec1*
 */
type ProjectSpec1SliceVariation = ProjectSpec1SliceDefault;

/**
 * ProjectSpec1 Shared Slice
 *
 * - **API ID**: `project_spec1`
 * - **Description**: ProjectSpec1
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectSpec1Slice = prismic.SharedSlice<
  "project_spec1",
  ProjectSpec1SliceVariation
>;

/**
 * Primary content in *ProjectSpec2 → Primary*
 */
export interface ProjectSpec2SliceDefaultPrimary {
  /**
   * Title field in *ProjectSpec2 → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: project_spec2.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Body field in *ProjectSpec2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_spec2.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button Link field in *ProjectSpec2 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project_spec2.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button Label field in *ProjectSpec2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_spec2.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Image field in *ProjectSpec2 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_spec2.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *ProjectSpec2 → Items*
 */
export interface ProjectSpec2SliceDefaultItem {
  /**
   * Percentage field in *ProjectSpec2 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_spec2.items[].percentage
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  percentage: prismic.RichTextField;

  /**
   * Description field in *ProjectSpec2 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_spec2.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for ProjectSpec2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectSpec2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectSpec2SliceDefaultPrimary>,
  Simplify<ProjectSpec2SliceDefaultItem>
>;

/**
 * Slice variation for *ProjectSpec2*
 */
type ProjectSpec2SliceVariation = ProjectSpec2SliceDefault;

/**
 * ProjectSpec2 Shared Slice
 *
 * - **API ID**: `project_spec2`
 * - **Description**: ProjectSpec2
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectSpec2Slice = prismic.SharedSlice<
  "project_spec2",
  ProjectSpec2SliceVariation
>;

/**
 * Primary content in *ProjectsHeader → Primary*
 */
export interface ProjectsHeaderSliceDefaultPrimary {
  /**
   * Title field in *ProjectsHeader → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_header.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Body field in *ProjectsHeader → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_header.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for ProjectsHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectsHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectsHeader*
 */
type ProjectsHeaderSliceVariation = ProjectsHeaderSliceDefault;

/**
 * ProjectsHeader Shared Slice
 *
 * - **API ID**: `projects_header`
 * - **Description**: ProjectsHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsHeaderSlice = prismic.SharedSlice<
  "projects_header",
  ProjectsHeaderSliceVariation
>;

/**
 * Primary content in *RichText → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *SecondaryCta → Primary*
 */
export interface SecondaryCtaSliceDefaultPrimary {
  /**
   * Title field in *SecondaryCta → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: secondary_cta.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Body field in *SecondaryCta → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: secondary_cta.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button Link field in *SecondaryCta → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: secondary_cta.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button Label field in *SecondaryCta → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: secondary_cta.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;
}

/**
 * Default variation for SecondaryCta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecondaryCtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SecondaryCtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SecondaryCta*
 */
type SecondaryCtaSliceVariation = SecondaryCtaSliceDefault;

/**
 * SecondaryCta Shared Slice
 *
 * - **API ID**: `secondary_cta`
 * - **Description**: SecondaryCta
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecondaryCtaSlice = prismic.SharedSlice<
  "secondary_cta",
  SecondaryCtaSliceVariation
>;

/**
 * Primary content in *ServiceBenefits → Primary*
 */
export interface ServiceBenefitsSliceDefaultPrimary {
  /**
   * Title field in *ServiceBenefits → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: service_benefits.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Body field in *ServiceBenefits → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_benefits.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button1Link field in *ServiceBenefits → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: service_benefits.primary.button1link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button1link: prismic.LinkField;

  /**
   * Button2Label field in *ServiceBenefits → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_benefits.primary.button2label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button2label: prismic.KeyTextField;

  /**
   * Button2Link field in *ServiceBenefits → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: service_benefits.primary.button2link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button2link: prismic.LinkField;

  /**
   * Button2Text field in *ServiceBenefits → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_benefits.primary.button2text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button2text: prismic.KeyTextField;

  /**
   * Image field in *ServiceBenefits → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_benefits.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ServiceBenefits Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceBenefitsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceBenefitsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServiceBenefits*
 */
type ServiceBenefitsSliceVariation = ServiceBenefitsSliceDefault;

/**
 * ServiceBenefits Shared Slice
 *
 * - **API ID**: `service_benefits`
 * - **Description**: ServiceBenefits
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceBenefitsSlice = prismic.SharedSlice<
  "service_benefits",
  ServiceBenefitsSliceVariation
>;

/**
 * Primary content in *ServiceFeatures → Primary*
 */
export interface ServiceFeaturesSliceDefaultPrimary {
  /**
   * Image field in *ServiceFeatures → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_features.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *ServiceFeatures → Items*
 */
export interface ServiceFeaturesSliceDefaultItem {
  /**
   * Title field in *ServiceFeatures → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: service_features.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Body field in *ServiceFeatures → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_features.items[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for ServiceFeatures Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceFeaturesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceFeaturesSliceDefaultPrimary>,
  Simplify<ServiceFeaturesSliceDefaultItem>
>;

/**
 * Slice variation for *ServiceFeatures*
 */
type ServiceFeaturesSliceVariation = ServiceFeaturesSliceDefault;

/**
 * ServiceFeatures Shared Slice
 *
 * - **API ID**: `service_features`
 * - **Description**: ServiceFeatures
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceFeaturesSlice = prismic.SharedSlice<
  "service_features",
  ServiceFeaturesSliceVariation
>;

/**
 * Primary content in *ServiceFields → Primary*
 */
export interface ServiceFieldsSliceDefaultPrimary {
  /**
   * Title field in *ServiceFields → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: service_fields.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Primary content in *ServiceFields → Items*
 */
export interface ServiceFieldsSliceDefaultItem {
  /**
   * Icons field in *ServiceFields → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Construction
   * - **API ID Path**: service_fields.items[].icons
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icons: prismic.SelectField<"Construction" | "Hammer", "filled">;

  /**
   * Header field in *ServiceFields → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: service_fields.items[].header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.TitleField;

  /**
   * Description field in *ServiceFields → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_fields.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for ServiceFields Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceFieldsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceFieldsSliceDefaultPrimary>,
  Simplify<ServiceFieldsSliceDefaultItem>
>;

/**
 * Slice variation for *ServiceFields*
 */
type ServiceFieldsSliceVariation = ServiceFieldsSliceDefault;

/**
 * ServiceFields Shared Slice
 *
 * - **API ID**: `service_fields`
 * - **Description**: ServiceFields
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceFieldsSlice = prismic.SharedSlice<
  "service_fields",
  ServiceFieldsSliceVariation
>;

/**
 * Primary content in *ServiceHeader → Primary*
 */
export interface ServiceHeaderSliceDefaultPrimary {
  /**
   * Title field in *ServiceHeader → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: service_header.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Body field in *ServiceHeader → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_header.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Image field in *ServiceHeader → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_header.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Button Link field in *ServiceHeader → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: service_header.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button Label field in *ServiceHeader → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_header.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;
}

/**
 * Default variation for ServiceHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServiceHeader*
 */
type ServiceHeaderSliceVariation = ServiceHeaderSliceDefault;

/**
 * ServiceHeader Shared Slice
 *
 * - **API ID**: `service_header`
 * - **Description**: ServiceHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceHeaderSlice = prismic.SharedSlice<
  "service_header",
  ServiceHeaderSliceVariation
>;

/**
 * Primary content in *ServiceProcess → Primary*
 */
export interface ServiceProcessSliceDefaultPrimary {
  /**
   * Heading field in *ServiceProcess → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: service_process.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;
}

/**
 * Primary content in *ServiceProcess → Items*
 */
export interface ServiceProcessSliceDefaultItem {
  /**
   * Image field in *ServiceProcess → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_process.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *ServiceProcess → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: service_process.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Body field in *ServiceProcess → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_process.items[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for ServiceProcess Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceProcessSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceProcessSliceDefaultPrimary>,
  Simplify<ServiceProcessSliceDefaultItem>
>;

/**
 * Slice variation for *ServiceProcess*
 */
type ServiceProcessSliceVariation = ServiceProcessSliceDefault;

/**
 * ServiceProcess Shared Slice
 *
 * - **API ID**: `service_process`
 * - **Description**: ServiceProcess
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceProcessSlice = prismic.SharedSlice<
  "service_process",
  ServiceProcessSliceVariation
>;

/**
 * Primary content in *Services → Primary*
 */
export interface ServicesSliceDefaultPrimary {
  /**
   * Title field in *Services → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: services.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Body field in *Services → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button Link field in *Services → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button Label field in *Services → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;
}

/**
 * Primary content in *Services → Items*
 */
export interface ServicesSliceDefaultItem {
  /**
   * Icon field in *Services → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: services.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<"Bulb" | "House" | "Hammer" | "Construction">;

  /**
   * Title field in *Services → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: services.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Body field in *Services → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.items[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSliceDefaultPrimary>,
  Simplify<ServicesSliceDefaultItem>
>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault;

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSlice = prismic.SharedSlice<
  "services",
  ServicesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CaseStudyDocument,
      CaseStudyDocumentData,
      CaseStudyDocumentDataSlicesSlice,
      OperationsDocument,
      OperationsDocumentData,
      OperationsDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      AllDocumentTypes,
      AboutHeaderSlice,
      AboutHeaderSliceDefaultPrimary,
      AboutHeaderSliceVariation,
      AboutHeaderSliceDefault,
      AboutHistorySlice,
      AboutHistorySliceDefaultPrimary,
      AboutHistorySliceDefaultItem,
      AboutHistorySliceVariation,
      AboutHistorySliceDefault,
      AboutTimelineSlice,
      AboutTimelineSliceDefaultPrimary,
      AboutTimelineSliceDefaultItem,
      AboutTimelineSliceVariation,
      AboutTimelineSliceDefault,
      CarousalSlice,
      CarousalSliceDefaultPrimary,
      CarousalSliceDefaultItem,
      CarousalSliceVariation,
      CarousalSliceDefault,
      CaseStudySlice,
      CaseStudySliceDefaultItem,
      CaseStudySliceVariation,
      CaseStudySliceDefault,
      ContactSlice,
      ContactSliceDefaultPrimary,
      ContactSliceDefaultItem,
      ContactSliceVariation,
      ContactSliceDefault,
      ContactFormSlice,
      ContactFormSliceDefaultPrimary,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      ContactHeaderSlice,
      ContactHeaderSliceDefaultPrimary,
      ContactHeaderSliceVariation,
      ContactHeaderSliceDefault,
      CtaSlice,
      CtaSliceDefaultPrimary,
      CtaSliceVariation,
      CtaSliceDefault,
      FaqSlice,
      FaqSliceDefaultPrimary,
      FaqSliceDefaultItem,
      FaqSliceVariation,
      FaqSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HomeAboutSlice,
      HomeAboutSliceDefaultPrimary,
      HomeAboutSliceVariation,
      HomeAboutSliceDefault,
      HomeAbout2Slice,
      HomeAbout2SliceDefaultPrimary,
      HomeAbout2SliceVariation,
      HomeAbout2SliceDefault,
      HomeTeamSlice,
      HomeTeamSliceDefaultPrimary,
      HomeTeamSliceDefaultItem,
      HomeTeamSliceVariation,
      HomeTeamSliceDefault,
      OperationsSlice,
      OperationsSliceDefaultPrimary,
      OperationsSliceDefaultItem,
      OperationsSliceVariation,
      OperationsSliceDefault,
      OperationsHeaderSlice,
      OperationsHeaderSliceDefaultPrimary,
      OperationsHeaderSliceVariation,
      OperationsHeaderSliceDefault,
      ProjectSpec1Slice,
      ProjectSpec1SliceDefaultPrimary,
      ProjectSpec1SliceDefaultItem,
      ProjectSpec1SliceVariation,
      ProjectSpec1SliceDefault,
      ProjectSpec2Slice,
      ProjectSpec2SliceDefaultPrimary,
      ProjectSpec2SliceDefaultItem,
      ProjectSpec2SliceVariation,
      ProjectSpec2SliceDefault,
      ProjectsHeaderSlice,
      ProjectsHeaderSliceDefaultPrimary,
      ProjectsHeaderSliceVariation,
      ProjectsHeaderSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SecondaryCtaSlice,
      SecondaryCtaSliceDefaultPrimary,
      SecondaryCtaSliceVariation,
      SecondaryCtaSliceDefault,
      ServiceBenefitsSlice,
      ServiceBenefitsSliceDefaultPrimary,
      ServiceBenefitsSliceVariation,
      ServiceBenefitsSliceDefault,
      ServiceFeaturesSlice,
      ServiceFeaturesSliceDefaultPrimary,
      ServiceFeaturesSliceDefaultItem,
      ServiceFeaturesSliceVariation,
      ServiceFeaturesSliceDefault,
      ServiceFieldsSlice,
      ServiceFieldsSliceDefaultPrimary,
      ServiceFieldsSliceDefaultItem,
      ServiceFieldsSliceVariation,
      ServiceFieldsSliceDefault,
      ServiceHeaderSlice,
      ServiceHeaderSliceDefaultPrimary,
      ServiceHeaderSliceVariation,
      ServiceHeaderSliceDefault,
      ServiceProcessSlice,
      ServiceProcessSliceDefaultPrimary,
      ServiceProcessSliceDefaultItem,
      ServiceProcessSliceVariation,
      ServiceProcessSliceDefault,
      ServicesSlice,
      ServicesSliceDefaultPrimary,
      ServicesSliceDefaultItem,
      ServicesSliceVariation,
      ServicesSliceDefault,
    };
  }
}
