// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_header: dynamic(() => import("./AboutHeader")),
  about_history: dynamic(() => import("./AboutHistory")),
  about_timeline: dynamic(() => import("./AboutTimeline")),
  carousal: dynamic(() => import("./Carousal")),
  case_study: dynamic(() => import("./CaseStudy")),
  contact: dynamic(() => import("./Contact")),
  contact_form: dynamic(() => import("./ContactForm")),
  contact_header: dynamic(() => import("./ContactHeader")),
  cta: dynamic(() => import("./Cta")),
  faq: dynamic(() => import("./Faq")),
  hero: dynamic(() => import("./Hero")),
  home_about: dynamic(() => import("./HomeAbout")),
  home_about2: dynamic(() => import("./HomeAbout2")),
  home_team: dynamic(() => import("./HomeTeam")),
  operations: dynamic(() => import("./Operations")),
  operations_header: dynamic(() => import("./OperationsHeader")),
  project_spec1: dynamic(() => import("./ProjectSpec1")),
  project_spec2: dynamic(() => import("./ProjectSpec2")),
  projects_header: dynamic(() => import("./ProjectsHeader")),
  rich_text: dynamic(() => import("./RichText")),
  secondary_cta: dynamic(() => import("./SecondaryCta")),
  service_benefits: dynamic(() => import("./ServiceBenefits")),
  service_features: dynamic(() => import("./ServiceFeatures")),
  service_fields: dynamic(() => import("./ServiceFields")),
  service_header: dynamic(() => import("./ServiceHeader")),
  service_process: dynamic(() => import("./ServiceProcess")),
  services: dynamic(() => import("./Services")),
};
