// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_header: dynamic(() => import("./AboutHeader")),
  about_history: dynamic(() => import("./AboutHistory")),
  contact: dynamic(() => import("./Contact")),
  cta: dynamic(() => import("./Cta")),
  faq: dynamic(() => import("./Faq")),
  hero: dynamic(() => import("./Hero")),
  home_about: dynamic(() => import("./HomeAbout")),
  home_about2: dynamic(() => import("./HomeAbout2")),
  home_team: dynamic(() => import("./HomeTeam")),
  rich_text: dynamic(() => import("./RichText")),
  services: dynamic(() => import("./Services")),
};
